version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: my-backend
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: my-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped